version: '3'
services: 
    api-mongo:
        build: .
        ports: 
            - "3001:3001"
        volumes: 
            - ./:/usr/src/app/api/
            - /usr/src/app/api/node_modules
        environment: 
            - PORT=3001